# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AffineGroupbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AffineTransForm(object):
    def setupUi(self, AffineTransForm):
        AffineTransForm.setObjectName("AffineTransForm")
        AffineTransForm.resize(640, 480)
        self.groupBox_Congfiguation = QtWidgets.QGroupBox(AffineTransForm)
        self.groupBox_Congfiguation.setGeometry(QtCore.QRect(150, 110, 331, 170))
        self.groupBox_Congfiguation.setObjectName("groupBox_Congfiguation")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_Congfiguation)
        self.gridLayout_3.setContentsMargins(5, 10, 5, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_12 = QtWidgets.QLabel(self.groupBox_Congfiguation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.comboBox_Model = QtWidgets.QComboBox(self.groupBox_Congfiguation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Model.sizePolicy().hasHeightForWidth())
        self.comboBox_Model.setSizePolicy(sizePolicy)
        self.comboBox_Model.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_Model.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox_Model.setObjectName("comboBox_Model")
        self.comboBox_Model.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_Model, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_Congfiguation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 2)
        self.comboBox_CoordType = QtWidgets.QComboBox(self.groupBox_Congfiguation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_CoordType.sizePolicy().hasHeightForWidth())
        self.comboBox_CoordType.setSizePolicy(sizePolicy)
        self.comboBox_CoordType.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_CoordType.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox_CoordType.setObjectName("comboBox_CoordType")
        self.comboBox_CoordType.addItem("")
        self.comboBox_CoordType.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_CoordType, 1, 2, 1, 1)
        self.gridLayout_3.setRowStretch(0, 1)

        self.retranslateUi(AffineTransForm)
        QtCore.QMetaObject.connectSlotsByName(AffineTransForm)

    def retranslateUi(self, AffineTransForm):
        _translate = QtCore.QCoreApplication.translate
        AffineTransForm.setWindowTitle(_translate("AffineTransForm", "Form"))
        self.groupBox_Congfiguation.setTitle(_translate("AffineTransForm", "Configuarion"))
        self.label_12.setText(_translate("AffineTransForm", "Model"))
        self.comboBox_Model.setItemText(0, _translate("AffineTransForm", "Gx2DAffineTrans"))
        self.label_13.setText(_translate("AffineTransForm", "Coordinate Type"))
        self.comboBox_CoordType.setItemText(0, _translate("AffineTransForm", "XY"))
        self.comboBox_CoordType.setItemText(1, _translate("AffineTransForm", "BL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AffineTransForm = QtWidgets.QWidget()
    ui = Ui_AffineTransForm()
    ui.setupUi(AffineTransForm)
    AffineTransForm.show()
    sys.exit(app.exec_())
