# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_TXT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.Qt import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_TXT(object):
    def setupUi(self, Dialog_TXT):
        Dialog_TXT.setObjectName("Dialog_TXT")
        Dialog_TXT.resize(264, 161)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_TXT)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog_TXT)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Dialog_TXT)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog_TXT)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog_TXT)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_TXT)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)

        self.retranslateUi(Dialog_TXT)
        self.buttonBox.accepted.connect(Dialog_TXT.accept)
        self.buttonBox.rejected.connect(Dialog_TXT.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_TXT)

    def retranslateUi(self, Dialog_TXT):
        _translate = QtCore.QCoreApplication.translate
        Dialog_TXT.setWindowTitle(_translate("Dialog_TXT", "Dialog"))
        self.label.setText(_translate("Dialog_TXT", "Separator"))
        self.lineEdit.setText(_translate("Dialog_TXT", ","))
        self.label_2.setText(_translate("Dialog_TXT", "Encoding"))
        self.lineEdit_2.setText(_translate("Dialog_TXT", "utf-8"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_TXT = QtWidgets.QDialog()
    ui = Ui_Dialog_TXT()
    ui.setupUi(Dialog_TXT)
    Dialog_TXT.show()
    sys.exit(app.exec_())
