# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PolyfitGroupbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PolyfitForm(object):
    def setupUi(self, PolyfitForm):
        PolyfitForm.setObjectName("PolyfitForm")
        PolyfitForm.resize(640, 480)
        self.groupBox_Congfiguation = QtWidgets.QGroupBox(PolyfitForm)
        self.groupBox_Congfiguation.setGeometry(QtCore.QRect(140, 170, 347, 128))
        self.groupBox_Congfiguation.setObjectName("groupBox_Congfiguation")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_Congfiguation)
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(self.groupBox_Congfiguation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.comboBox_Model = QtWidgets.QComboBox(self.groupBox_Congfiguation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Model.sizePolicy().hasHeightForWidth())
        self.comboBox_Model.setSizePolicy(sizePolicy)
        self.comboBox_Model.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_Model.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox_Model.setObjectName("comboBox_Model")
        self.comboBox_Model.addItem("")
        self.gridLayout.addWidget(self.comboBox_Model, 0, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.groupBox_Congfiguation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.comboBox_CoordType = QtWidgets.QComboBox(self.groupBox_Congfiguation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_CoordType.sizePolicy().hasHeightForWidth())
        self.comboBox_CoordType.setSizePolicy(sizePolicy)
        self.comboBox_CoordType.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_CoordType.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox_CoordType.setObjectName("comboBox_CoordType")
        self.comboBox_CoordType.addItem("")
        self.comboBox_CoordType.addItem("")
        self.gridLayout.addWidget(self.comboBox_CoordType, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_Congfiguation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 2)
        self.comboBox_Order = QtWidgets.QComboBox(self.groupBox_Congfiguation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Order.sizePolicy().hasHeightForWidth())
        self.comboBox_Order.setSizePolicy(sizePolicy)
        self.comboBox_Order.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_Order.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox_Order.setObjectName("comboBox_Order")
        self.comboBox_Order.addItem("")
        self.comboBox_Order.addItem("")
        self.gridLayout.addWidget(self.comboBox_Order, 2, 2, 1, 1)

        self.retranslateUi(PolyfitForm)
        QtCore.QMetaObject.connectSlotsByName(PolyfitForm)

    def retranslateUi(self, PolyfitForm):
        _translate = QtCore.QCoreApplication.translate
        PolyfitForm.setWindowTitle(_translate("PolyfitForm", "Form"))
        self.groupBox_Congfiguation.setTitle(_translate("PolyfitForm", "Configuarion"))
        self.label_12.setText(_translate("PolyfitForm", "Model"))
        self.comboBox_Model.setItemText(0, _translate("PolyfitForm", "Gx2DPolynomialFitTrans"))
        self.label_13.setText(_translate("PolyfitForm", "Coordinate Type"))
        self.comboBox_CoordType.setItemText(0, _translate("PolyfitForm", "XY"))
        self.comboBox_CoordType.setItemText(1, _translate("PolyfitForm", "BL"))
        self.label_14.setText(_translate("PolyfitForm", "Order"))
        self.comboBox_Order.setItemText(0, _translate("PolyfitForm", "Quadratic polynomial"))
        self.comboBox_Order.setItemText(1, _translate("PolyfitForm", "Cubic polynomial"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PolyfitForm = QtWidgets.QWidget()
    ui = Ui_PolyfitForm()
    ui.setupUi(PolyfitForm)
    PolyfitForm.show()
    sys.exit(app.exec_())
